export const loginFormJson = {
  widgetList: [
    {
      key: 98722,
      type: "grid",
      category: "container",
      icon: "grid",
      cols: [
        {
          type: "grid-col",
          category: "container",
          icon: "grid-col",
          internal: true,
          widgetList: [],
          options: {
            name: "gridCol59831",
            hidden: false,
            span: 15,
            offset: 0,
            push: 0,
            pull: 0,
            responsive: false,
            md: 12,
            sm: 12,
            xs: 12,
            customClass: ["left-decoration"],
          },
          id: "grid-col-59831",
        },
        {
          type: "grid-col",
          category: "container",
          icon: "grid-col",
          internal: true,
          widgetList: [
            {
              key: 98722,
              type: "grid",
              category: "container",
              icon: "grid",
              cols: [
                {
                  type: "grid-col",
                  category: "container",
                  icon: "grid-col",
                  internal: true,
                  widgetList: [
                    {
                      type: "static-text",
                      icon: "static-text",
                      category: "field",
                      options: {
                        name: "platformTitle",
                        title: "CPIOT物联平台",
                        comsize: "",
                        status: "",
                        icon: "",
                        clickToCopy: false,
                        hidden: false,
                        fontFamily: "Arial, sans-serif",
                        fontSize: 28,
                        fontWeight: "bold",
                        fontStyle: "normal",
                        lineHeight: 1.5,
                        comtextAlign: "left",
                        textDecoration: "none",
                        textTransform: "none",
                        letterSpacing: 0,
                        textIndent: 0,
                        customClass: [
                          "platform-title",
                          "fade-in-up",
                          "delay-1",
                        ],
                        label: "static-text",
                      },
                      id: "platformTitle",
                    },
                  ],
                  options: {
                    name: "gridCol56155",
                    hidden: false,
                    span: 24,
                    offset: 0,
                    push: 0,
                    pull: 0,
                    responsive: false,
                    md: 12,
                    sm: 12,
                    xs: 12,
                    customClass: [],
                  },
                  id: "grid-col-56155",
                },
                {
                  type: "grid-col",
                  category: "container",
                  icon: "grid-col",
                  internal: true,
                  widgetList: [
                    {
                      type: "static-text",
                      icon: "static-text",
                      category: "field",
                      options: {
                        name: "welcomeText",
                        title: "欢迎登录",
                        comsize: "",
                        status: "",
                        icon: "",
                        clickToCopy: false,
                        hidden: false,
                        fontFamily: "Arial, sans-serif",
                        fontSize: 24,
                        fontWeight: "normal",
                        fontStyle: "normal",
                        lineHeight: 1.5,
                        comtextAlign: "left",
                        textDecoration: "none",
                        textTransform: "none",
                        letterSpacing: 0,
                        textIndent: 0,
                        customClass: ["welcome-text", "fade-in-up", "delay-2"],
                        label: "static-text",
                      },
                      id: "welcomeText",
                    },
                  ],
                  options: {
                    name: "gridCol93653",
                    hidden: false,
                    span: 24,
                    offset: 0,
                    push: 0,
                    pull: 0,
                    responsive: false,
                    md: 12,
                    sm: 12,
                    xs: 12,
                    customClass: [],
                  },
                  id: "grid-col-93653",
                },
                {
                  type: "grid-col",
                  category: "container",
                  icon: "grid-col",
                  internal: true,
                  widgetList: [
                    {
                      type: "input",
                      icon: "input",
                      formItemFlag: true,
                      options: {
                        name: "username",
                        label: "账号",
                        labelAlign: "label-left-align",
                        type: "text",
                        defaultValue: "admin",
                        placeholder: "请输入账号",
                        columnWidth: "100%",
                        size: "",
                        labelWidth: 60,
                        labelHidden: false,
                        readonly: false,
                        disabled: false,
                        hidden: false,
                        clearable: true,
                        showPassword: false,
                        required: true,
                        requiredHint: "请输入账号",
                        validation: "",
                        validationHint: "",
                        customClass: ["login-input", "fade-in-up", "delay-3"],
                        labelIconClass: null,
                        labelIconPosition: "front",
                        labelTooltip: null,
                        minLength: 3,
                        maxLength: null,
                        showWordLimit: false,
                        prefixIcon: "vxe-icon-user",
                        suffixIcon: "",
                        appendButton: false,
                        appendButtonDisabled: false,
                        buttonIcon: "",
                        appendButtonType: "primary",
                        onCreated: "",
                        onMounted: "",
                        onInput: "",
                        onChange: "",
                        onFocus: "",
                        onBlur: "",
                        onAppendButtonClick: "",
                      },
                      id: "username",
                    },
                  ],
                  options: {
                    name: "gridCol12845",
                    hidden: false,
                    span: 24,
                    offset: 0,
                    push: 0,
                    pull: 0,
                    responsive: false,
                    md: 12,
                    sm: 12,
                    xs: 12,
                    customClass: [],
                  },
                  id: "grid-col-12845",
                },
                {
                  type: "grid-col",
                  category: "container",
                  icon: "grid-col",
                  internal: true,
                  widgetList: [
                    {
                      type: "password",
                      icon: "password",
                      formItemFlag: true,
                      options: {
                        name: "password",
                        label: "密码",
                        labelAlign: "label-left-align",
                        type: "password",
                        defaultValue: "",
                        placeholder: "请输入密码",
                        columnWidth: "100%",
                        size: "",
                        labelWidth: 60,
                        labelHidden: false,
                        readonly: false,
                        disabled: false,
                        hidden: false,
                        clearable: true,
                        showPassword: true,
                        required: true,
                        requiredHint: "请输入密码",
                        validation: "",
                        validationHint: "",
                        customClass: ["login-input", "fade-in-up", "delay-4"],
                        labelIconClass: null,
                        labelIconPosition: "front",
                        labelTooltip: null,
                        minLength: 5,
                        maxLength: null,
                        showWordLimit: false,
                        prefixIcon: "vxe-icon-lock",
                        suffixIcon: "",
                        appendButton: false,
                        appendButtonDisabled: false,
                        buttonIcon: "",
                        appendButtonType: "primary",
                        onCreated: "",
                        onMounted: "",
                        onInput: "",
                        onChange: "",
                        onFocus: "",
                        onBlur: "",
                        onAppendButtonClick: "",
                      },
                      id: "password",
                    },
                  ],
                  options: {
                    name: "gridCol26953",
                    hidden: false,
                    span: 24,
                    offset: 0,
                    push: 0,
                    pull: 0,
                    responsive: false,
                    md: 12,
                    sm: 12,
                    xs: 12,
                    customClass: [],
                  },
                  id: "grid-col-26953",
                },
                {
                  type: "grid-col",
                  category: "container",
                  icon: "grid-col",
                  internal: true,
                  widgetList: [
                    {
                      key: 37087,
                      type: "checkbox-group",
                      icon: "checkbox-field",
                      category: "field",
                      isnew: "9",
                      formItemFlag: true,
                      checkboxs: [
                        {
                          type: "checkbox",
                          category: "container",
                          icon: "checkbox",
                          internal: true,
                          formItemFlag: false,
                          widgetList: [],
                          options: {
                            name: "checkbox1",
                            label: 1,
                            title: "记住密码",
                            disabled: false,
                            hidden: false,
                            customClass: [],
                          },
                          id: "checkbox1",
                        },
                      ],
                      options: {
                        name: "rememberMe",
                        label: "",
                        title: "复选框组",
                        checkboxType: "checkboxType",
                        commax: 0,
                        direction: "row",
                        comsize: "",
                        gap: 0,
                        vmodel: [],
                        hidden: false,
                        customClass: ["remember-me"],
                        onCreated: "",
                        onMounted: "",
                        onChange: "",
                        onValidate: "",
                      },
                      id: "checkboxgroup73009",
                    },
                    {
                      key: 78476,
                      type: "button",
                      icon: "button",
                      category: "field",
                      isnew: "9",
                      options: {
                        name: "loginButton",
                        title: "登录",
                        belongTo: "",
                        mode: "button",
                        float: "center",
                        comsize: "",
                        status: "primary",
                        round: false,
                        circle: false,
                        icon: "",
                        prefixTooltip: "",
                        suffixTooltip: "",
                        loading: false,
                        comdisabled: false,
                        hidden: false,
                        customClass: ["login-button"],
                        onCreated: "",
                        onMounted: "",
                        onClick: "",
                        label: "button",
                      },
                      id: "button71287",
                    },
                  ],
                  options: {
                    name: "gridCol45832",
                    hidden: false,
                    span: 24,
                    offset: 0,
                    push: 0,
                    pull: 0,
                    responsive: false,
                    md: 12,
                    sm: 12,
                    xs: 12,
                    customClass: [],
                  },
                  id: "grid-col-45832",
                },
              ],
              options: {
                name: "grid85814",
                hidden: false,
                gutter: 12,
                colHeight: null,
                customClass: [],
              },
              id: "grid85814",
            },
          ],
          options: {
            name: "gridCol79678",
            hidden: false,
            span: 9,
            offset: 0,
            push: 0,
            pull: 0,
            responsive: false,
            md: 12,
            sm: 12,
            xs: 12,
            customClass: ["login-panel"],
          },
          id: "grid-col-79678",
        },
      ],
      options: {
        name: "grid74043",
        hidden: false,
        gutter: 12,
        colHeight: "",
        customClass: ["bg"],
      },
      id: "grid74043",
    },
  ],
  formConfig: {
    modelName: "formData",
    refName: "vForm",
    rulesName: "rules",
    labelWidth: 120,
    labelPosition: "right",
    size: "",
    labelAlign: "label-right-align",
    cssCode:
      "/* 全局样式 */\n* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n  font-family: 'Arial', sans-serif;\n}\n\n/* 背景和全局布局 */\n.bg {\n  width: 100%;\n  height: 100%;\n  background-image: url('/img/login-bg.png');\n  background-size: cover;\n  background-position: center;\n  background-repeat: no-repeat;\n  display: flex;\n  align-items: center;\n  justify-content: flex-end;\n  position: relative;\n}\n\n.h100 {\n  height: 100vh;\n}\n\n.w100 {\n  width: 100%;\n}\n\n/* 登录面板样式 */\n.login-panel {\n  background-color: rgba(255, 255, 255, 0.9);\n  border-radius: 12px;\n  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);\n  padding: 30px;\n  max-width: 400px;\n  min-height: 450px;\n  margin-right: 50px;\n  backdrop-filter: blur(10px);\n  -webkit-backdrop-filter: blur(10px);\n  animation: fadeIn 0.6s ease-in-out;\n}\n\n@keyframes fadeIn {\n  from { opacity: 0; transform: translateY(20px); }\n  to { opacity: 1; transform: translateY(0); }\n}\n\n/* 平台标题样式 */\n.platform-title {\n  color: #2368f0;\n  margin-bottom: 15px;\n  font-size: 28px !important;\n  display: block;\n  text-align: center !important;\n  font-weight: bold !important;\n  background: linear-gradient(45deg, #2368f0, #00aeff);\n  -webkit-background-clip: text;\n  -webkit-text-fill-color: transparent;\n  letter-spacing: 1px;\n}\n\n/* 欢迎文本样式 */\n.welcome-text {\n  color: #333;\n  margin-bottom: 30px;\n  font-size: 20px !important;\n  text-align: center !important;\n  display: block;\n  font-weight: 500 !important;\n}\n\n/* 输入框样式 */\n.login-input .vxe-input {\n  border-radius: 8px !important;\n  height: 45px !important;\n  transition: all 0.3s;\n  background-color: rgba(245, 247, 250, 0.8) !important;\n  border: 1px solid #e0e5eb !important;\n}\n\n.login-input .vxe-input:focus-within {\n  border-color: #2368f0 !important;\n  box-shadow: 0 0 0 2px rgba(35, 104, 240, 0.2) !important;\n}\n\n.login-input .vxe-input--prefix-icon {\n  color: #2368f0 !important;\n  font-size: 18px !important;\n}\n\n.login-input .vxe-form-item__label {\n  font-weight: 500 !important;\n  color: #333 !important;\n}\n\n.login-input {\n  margin-bottom: 20px !important;\n}\n\n/* 记住密码复选框样式 */\n.remember-me {\n  margin-bottom: 20px;\n}\n\n.remember-me .vxe-checkbox {\n  margin-left: 0 !important;\n  color: #666;\n}\n\n.remember-me .vxe-checkbox:hover {\n  color: #2368f0;\n}\n\n/* 登录按钮样式 */\n.login-button {\n  width: 100% !important;\n  height: 45px !important;\n  border-radius: 8px !important;\n  font-size: 16px !important;\n  font-weight: 500 !important;\n  margin-top: 10px !important;\n  background: linear-gradient(45deg, #2368f0, #00aeff) !important;\n  border: none !important;\n  box-shadow: 0 4px 15px rgba(35, 104, 240, 0.3);\n  transition: all 0.3s;\n}\n\n.login-button:hover {\n  transform: translateY(-2px);\n  box-shadow: 0 6px 20px rgba(35, 104, 240, 0.4);\n}\n\n.login-button .vxe-button--content {\n  color: white;\n}\n\n.login-button>div{\n  width:100%;\n  height:100%;\n}\n\n.login-button button{\n  background: transparent !important;\n  border: none !important;  \n  height: 100% !important;\n  width: 100% !important;\n  line-height: 3 !important;\n}\n\n/* 内容区动画 */\n.fade-in-up {\n  animation: slideUp 0.5s ease-out;\n  animation-fill-mode: both;\n}\n\n.delay-1 { animation-delay: 0.1s; }\n.delay-2 { animation-delay: 0.2s; }\n.delay-3 { animation-delay: 0.3s; }\n.delay-4 { animation-delay: 0.4s; }\n\n@keyframes slideUp {\n  0% {\n    opacity: 0;\n    transform: translateY(20px);\n  }\n  100% {\n    opacity: 1;\n    transform: translateY(0);\n  }\n}\n\n/* 左侧装饰区域 */\n.left-decoration {\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}\n\n/* 响应式调整 */\n@media screen and (max-width: 992px) {\n  .bg {\n    justify-content: center;\n  }\n  \n  .login-panel {\n    margin: 0 auto;\n    max-width: 90%;\n  }\n}",
    customClass: ["h100", "w100"],
    functions: "",
    layoutType: "PC",
    jsonVersion: 3,
    onFormCreated: "",
    onFormMounted: "initLoginPage",
    onFormDataChange: "",
    serviceMap: {},
    moduleId: "test2_login",
    // KITName: "test2",
    // KITCode: "test2",
    // KITFunCode: "login",
    moduleName: "test2",
    moduleCode: "test2",
    functionCode: "login",
    eventMap: {
      "form.onLoad": "initLoginPage",
      "button71287.onClick": "loginButton.onClick",
      "password.onKeyEnter": "password.onKeyEnter",
    },
    globalObject: {
      "loginButton.onClick":
        "function() {\n  // 获取表单数据\n try{  const username = this.formModel.username;\n  const password = this.formModel.password;\n  const rememberMe = this.formModel.rememberMe;\n  \n  // 表单验证\n  if (!username) {\n    this.Message.notifyError('请输入账号');\n    return;\n  }\n  \n  if (!password) {\n    this.Message.notifyError('请输入密码');\n    return;\n  }\n  \n  // 显示加载状态\n  const loginBtn = this.refList.loginButton;\n  loginBtn.setWidgetOption('loading', true);\n  \n  this.request.postData('/permission/login',{\n    username:this.dataCenter.encode(username),\n    password:this.dataCenter.encode(password) \n  }).then(res=>{\n  if (res.success) {\n      // 保存记住我选项\n      if (this.formModel.rememberMe) {\n        localStorage.setItem('rememberedUser', username);\n        localStorage.setItem('rememberedPassword', password);\n      } else {\n        localStorage.removeItem('rememberedUser');\n        localStorage.removeItem('rememberedPassword');\n      }\n    if(this.dataCenter)  this.dataCenter.postEvent('login-submit', {\n        token: res.data.tokenValue,\n        tokenName: res.data.tokenName,\n        userInfo: res.data.userInfo\n      });\n      \n      this.Message.notifySuccess(res.msg);\n    } else {\n      this.Message.notifyError(res.msg);\n    }\n  }).finally(()=>{\n      loginBtn.setWidgetOption('loading', false);\n  })} catch(e){ loginBtn.setWidgetOption('loading', false);\n}\n \n}",
      initLoginPage:
        "function() {\n    this.dataCenter.getkey() \n // 检查是否有保存的登录信息\n  const savedUsername = localStorage.getItem('rememberedUser');\n  const savedPassword = localStorage.getItem('rememberedPassword');\n  \n  if (savedUsername) {\n    this.formData.username = savedUsername;\n    \n    if (savedPassword) {\n      this.formData.password = savedPassword;\n      this.formData.rememberMe = true;\n    }\n  }\n  \n    }",
      "password.onKeyEnter":
        "function(event) {\n    // 按下回车键时触发登录\n  if (event.key === 'Enter') {\n    // 调用登录按钮的点击事件\n    const loginBtn = this.refList.loginButton;\n    if (loginBtn) {\n      this.formConfig.globalObject['loginButton.onClick'].call(this);\n    }\n  }\n}",
    },
  },
};
